# Generated by Django 4.2.3 on 2023-07-14 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='miapp.persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='miapp.persona'),
            preserve_default=False,
        ),
    ]
